# Generated by Django 4.2.11 on 2024-04-04 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoReposicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=100)),
                ('quantidade', models.PositiveIntegerField()),
                ('fornecedor', models.CharField(max_length=100)),
                ('data_pedido', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Processado', 'Processado'), ('Cancelado', 'Cancelado')], default='Pendente', max_length=20)),
            ],
        ),
    ]
