# Generated by Django 4.2.11 on 2024-04-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replacements', '0002_remove_pedidoreposicao_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoreposicao',
            name='produto',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
